# Generated by Django 4.2.1 on 2023-05-25 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_meta_data'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
        """, """
            DELETE FROM store_collection
            WHERE title='collection1'
        """)
    ]
